# Generated by Django 3.2.23 on 2023-12-11 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
    ]
