# Generated by Django 3.2.23 on 2023-12-09 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_remove_service_available_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Boarding',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='service',
        ),
        migrations.RemoveField(
            model_name='availabletime',
            name='calendar',
        ),
        migrations.DeleteModel(
            name='Calendar',
        ),
    ]
