# Generated by Django 3.2.23 on 2023-12-11 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20231211_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='time_slot',
            field=models.TimeField(choices=[('08:00:00', '8 AM'), ('09:00:00', '9 AM'), ('10:00:00', '10 AM'), ('11:00:00', '11 AM'), ('12:00:00', '12 PM'), ('14:00:00', '2 PM'), ('15:00:00', '2 PM'), ('16:00:00', '4 PM'), ('17:00:00', '5 PM'), ('18:00:00', '6 PM'), ('19:00:00', '7 PM')], default='08:00:00'),
        ),
    ]
