# Generated by Django 3.2.23 on 2023-12-12 19:34

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20231212_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='date',
        ),
        migrations.AddField(
            model_name='availability',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2023, 12, 19, 19, 34, 4, 92718, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='availability',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
