# Generated by Django 3.2.23 on 2023-12-12 19:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_auto_20231212_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='availability',
        ),
        migrations.AlterField(
            model_name='availability',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2023, 12, 19, 19, 46, 8, 772592, tzinfo=utc)),
        ),
    ]
