# Generated by Django 3.2.23 on 2023-12-12 19:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_auto_20231212_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2023, 12, 19, 19, 50, 6, 359734, tzinfo=utc)),
        ),
    ]
