# Generated by Django 3.2.23 on 2023-12-11 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_timeslot_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='time',
        ),
        migrations.AddField(
            model_name='timeslot',
            name='times',
            field=models.ManyToManyField(choices=[('08:00:00', '8 AM'), ('09:00:00', '9 AM'), ('10:00:00', '10 AM'), ('11:00:00', '11 AM'), ('12:00:00', '12 PM'), ('13:00:00', '1 PM'), ('14:00:00', '2 PM'), ('15:00:00', '3 PM'), ('16:00:00', '4 PM'), ('17:00:00', '5 PM')], default='08:00:00', to='booking.Time'),
        ),
    ]
