# Generated by Django 3.2.23 on 2023-12-11 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_auto_20231211_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='times',
            field=models.ManyToManyField(blank=True, to='booking.Time'),
        ),
    ]
