# Generated by Django 3.2.23 on 2023-12-12 20:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_alter_availability_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='available',
        ),
        migrations.RemoveField(
            model_name='availability',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='availability',
            name='start_date',
        ),
        migrations.AddField(
            model_name='availability',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
