# Generated by Django 3.2.23 on 2023-12-11 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_alter_timeslot_times'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='times',
        ),
        migrations.DeleteModel(
            name='Time',
        ),
    ]
