# Generated by Django 3.2.23 on 2023-12-12 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_auto_20231212_2047'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Availability',
        ),
    ]
