# Generated by Django 3.2.23 on 2023-12-11 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_auto_20231211_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='timeslot',
            name='times',
            field=models.ManyToManyField(blank=True, choices=[('00:00:00', '12 AM'), ('01:00:00', '1 AM'), ('02:00:00', '2 AM'), ('03:00:00', '3 AM'), ('04:00:00', '4 AM'), ('05:00:00', '5 AM'), ('06:00:00', '6 AM'), ('07:00:00', '7 AM'), ('08:00:00', '8 AM'), ('09:00:00', '9 AM'), ('10:00:00', '10 AM'), ('11:00:00', '11 AM'), ('12:00:00', '12 PM'), ('13:00:00', '1 PM'), ('14:00:00', '2 PM'), ('15:00:00', '3 PM'), ('16:00:00', '4 PM'), ('17:00:00', '5 PM'), ('18:00:00', '6 PM'), ('19:00:00', '7 PM'), ('20:00:00', '8 PM'), ('21:00:00', '9 PM'), ('22:00:00', '10 PM'), ('23:00:00', '11 PM')], to='booking.Time'),
        ),
    ]
