# Generated by Django 3.2.23 on 2023-12-11 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_auto_20231211_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='time',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
