# Generated by Django 3.2.23 on 2023-12-11 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_alter_time_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='time',
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='times',
            field=models.ManyToManyField(blank=True, to='booking.Time'),
        ),
    ]
