# Generated by Django 3.2.23 on 2023-12-15 19:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_auto_20231212_2149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unavailable_from', models.DateField()),
                ('unavailable_to', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='booking',
            name='time_slot',
        ),
        migrations.AddField(
            model_name='booking',
            name='time',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
        migrations.DeleteModel(
            name='DateAvailability',
        ),
        migrations.DeleteModel(
            name='TimeSlot',
        ),
    ]
