# Generated by Django 3.2.23 on 2023-12-26 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_auto_20231215_1941'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={},
        ),
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(max_length=400),
        ),
        migrations.AlterField(
            model_name='service',
            name='content',
            field=models.TextField(max_length=400),
        ),
    ]
