# Generated by Django 3.2.23 on 2023-12-26 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_auto_20231226_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
            ],
            options={
                'verbose_name': 'Booking Time',
                'verbose_name_plural': 'Booking Times',
            },
        ),
    ]
