# Generated by Django 3.2.23 on 2023-12-26 17:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_bookingtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingtime',
            name='time',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
    ]
