# Generated by Django 3.2.23 on 2023-12-26 18:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0015_alter_bookingtime_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookingtime',
            options={},
        ),
        migrations.RenameField(
            model_name='bookingtime',
            old_name='time',
            new_name='start_time',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='time',
        ),
        migrations.AddField(
            model_name='booking',
            name='timeslot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.bookingtime'),
        ),
        migrations.AddField(
            model_name='bookingtime',
            name='end_time',
            field=models.TimeField(default=datetime.time(19, 0)),
        ),
    ]
