# Generated by Django 3.2.23 on 2023-12-26 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0016_auto_20231226_1816'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='timeslot',
            new_name='time',
        ),
        migrations.RenameField(
            model_name='bookingtime',
            old_name='start_time',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='bookingtime',
            name='end_time',
        ),
    ]
