# Generated by Django 3.2.23 on 2023-12-27 17:43

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0017_auto_20231226_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.bookingtime'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(check=models.Q(('end_date__gte', django.db.models.expressions.F('start_date'))), name='end_date_gte_start_date'),
        ),
    ]
