# Generated by Django 3.2.23 on 2023-12-27 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0018_auto_20231227_1743'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
