# Generated by Django 3.2.23 on 2024-01-03 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0019_delete_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='add_second_dog',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='additional_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
